[package]
name = "csv_generator"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.3.10", features = ["derive"] }

csv = "1.2.2"
serde = { version = "1.0.164", features = ["serde_derive"] }
